### ISSUE TITLE
Unterminated quoted string

### ISSUE THREAD

**Issue by MaXin-noob** [MCSManager/pty#2]
请问在树莓派上安装面板后，使用模拟终端启动服务会报如下的错误：
![image](https://user-images.githubusercontent.com/67451711/184674869-3c7845e0-a048-4b3f-8ae7-7d0038306262.png)

**Comment by yumao233** [comment]
请提供一下你的 启动命令，系统环境，CPU架构。

面板版本的话，应该是 9.5，毕竟目前只有这个版本有 Pty。

**Comment by zijiren233** [comment]
arm架构等待下个版本支持

**Comment by zijiren233** [comment]
> 请问在树莓派上安装面板后，使用模拟终端启动服务会报如下的错误： ![image](https://user-images.githubusercontent.com/67451711/184674869-3c7845e0-a048-4b3f-8ae7-7d0038306262.png)

你可以下载 [linux_arm64](https://github.com/MCSManager/pty/releases/tag/v1.2) 版本替换/opt/mcsmanager/daemon/pty文件并添加root 755权限
