### ISSUE TITLE
在编译时能不能顺带把arm32给加进去？？

### ISSUE THREAD

**Issue by Duck15** [MCSManager/pty#6]
在编译时能不能顺带把arm32给加进去？？
我打算把web和daemon(用于管理shell)跑在我的盒子(Hi3798mv100)上 
但是启动daemon时并不会自动下载pty文件:(
找到这里但是没有arm32编译版本:(
我自个再编译啥的太麻烦力，球球了
plz add the "arm32 pty" to the releases

**Comment by yumao233** [comment]
arm32？有点为难，你自己下载源代码编译吧。

**Comment by zijiren233** [comment]
已支持，可自行下载 https://github.com/MCSManager/pty/releases
